name: "Nix-CI"
on:
  pull_request:
  push:
    branches: [master]
jobs:
  Nix-CI:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: brechtserckx-openscad
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: make nix-build
    - run: nix-shell --run "echo 'Shell ok'"
    - run: nix-shell --run "make format-check"
    - run: nix-shell --run "make hlint"
